// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpainChampionship.Infrastructure.Persistence;

#nullable disable

namespace SpainChampionship.Infrastructure.Migrations
{
    [DbContext(typeof(SpainChampionshipContext))]
    [Migration("20250618120903_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SpainChampionship.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("d030d5e0-bb71-47e6-9026-adbf514d91a5"))
                        .HasColumnName("Id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("City");

                    b.Property<int>("CountOfDefeats")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountOfDefeats");

                    b.Property<int>("CountOfDraws")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountOfDraws");

                    b.Property<int>("CountOfVictories")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountOfVictories");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
